import type { MetadataRoute } from "next";

/**
 * /robots.txt — generated by Next.js metadata route.
 * Allows all crawlers, points to sitemap, disallows admin and admin API.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/admin", "/api/admin"],
    },
    sitemap: "https://rkresidency.in/sitemap.xml",
  };
}
