import type { MetadataRoute } from "next";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

/**
 * /sitemap.xml — generated by Next.js metadata route.
 * Includes all static pages + dynamic room/blog/offer/experience pages.
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = "https://rkresidency.in";
  const now = new Date();

  // Static pages
  const staticPages: MetadataRoute.Sitemap = [
    { url: `${baseUrl}/`, lastModified: now, changeFrequency: "weekly", priority: 1.0 },
    { url: `${baseUrl}/rooms`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${baseUrl}/experiences`, lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${baseUrl}/dining`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${baseUrl}/gallery`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/offers`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${baseUrl}/blog`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${baseUrl}/about`, lastModified: now, changeFrequency: "monthly", priority: 0.6 },
    { url: `${baseUrl}/contact`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/festivals`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
  ];

  // Dynamic pages — rooms
  const rooms = await db.room.findMany({ select: { slug: true, updatedAt: true } });
  const roomUrls: MetadataRoute.Sitemap = rooms.map((r) => ({
    url: `${baseUrl}/rooms/${r.slug}`,
    lastModified: r.updatedAt,
    changeFrequency: "weekly",
    priority: 0.8,
  }));

  // Dynamic pages — offers
  const offers = await db.offer.findMany({ select: { slug: true, createdAt: true } });
  const offerUrls: MetadataRoute.Sitemap = offers.map((o) => ({
    url: `${baseUrl}/offers/${o.slug}`,
    lastModified: o.createdAt,
    changeFrequency: "weekly",
    priority: 0.7,
  }));

  // Dynamic pages — blog posts
  const posts = await db.blogPost.findMany({
    where: { published: true },
    select: { slug: true, publishedAt: true },
  });
  const blogUrls: MetadataRoute.Sitemap = posts.map((p) => ({
    url: `${baseUrl}/blog/${p.slug}`,
    lastModified: p.publishedAt || now,
    changeFrequency: "monthly",
    priority: 0.7,
  }));

  // Experiences (static slugs — defined in code)
  const experienceSlugs = [
    "banke-bihari-mandir",
    "iskcon-krishna-balaram",
    "prem-mandir",
    "nidhivan",
    "yamuna-aarti-keshi-ghat",
  ];
  const experienceUrls: MetadataRoute.Sitemap = experienceSlugs.map((slug) => ({
    url: `${baseUrl}/experiences/${slug}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  return [...staticPages, ...roomUrls, ...offerUrls, ...blogUrls, ...experienceUrls];
}
